### PR TITLE
SQL script to prepare anonymized DB dumps

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_api/issues/708

Questions before the PR can be reviewed:
- [x] what password to use for accounts? (username is now ``user<user_id>``) + make sure the value is the correctly encrypted one
- [x] what data should be purged for user profiles?

Other data to remove?

### CODE REVIEW

**Comment by cbeauchesne** [comment]
> what data should be purged for user profiles?

I would say all but locales :  It would be conservative to purge everything, and later ask ourself the question if needed.

> what password to use for accounts? (username is now user<user_id>) + make sure the value is the correctly encrypted one

'c2corg' ?

**Comment by brunobesson** [comment]
>Questions before the PR can be reviewed

I agree with @cbeauchesne answer: the profiles should be emptied. Or replaced with a default content.
As for the password, any default password would be fine. Either `c2corg` or something similar, or a password identical to the username.

**Comment by asaunier** [comment]
This PR is ready to be reviewed.

It removes all sensitive data: authentication tokens, sso stuff, mailing lists registrations, preferences, users' private data (emails, usernames, passwords, etc.) as well as profiles and profiles archives data.

The users' names (and id) remain though in order to preserve the authors of the documents.
Usernames are replaced by ``user<user_id>``, faked emails are used and passwords are all replaced by "c2c".

The queries take about 3 min on c2c SA's dev server (with a quite old DB though):
```
UPDATE 51041
TRUNCATE TABLE
TRUNCATE TABLE
TRUNCATE TABLE
TRUNCATE TABLE
UPDATE 234
UPDATE 382
UPDATE 51041
UPDATE 51157
UPDATE 50123
UPDATE 55590
UPDATE 56873
UPDATE 54442
TRUNCATE TABLE
TRUNCATE TABLE
TRUNCATE TABLE
TRUNCATE TABLE
TRUNCATE TABLE
```

**Comment by asaunier** [comment]
@brunobesson Thanks!

**Pull request merged**
