### PR TITLE
Add user accounts merging script

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_ui/issues/1542

See todo list at https://github.com/c2corg/v6_ui/issues/1542#issuecomment-289080075

### CODE REVIEW

**Comment by asaunier** [comment]
Guidebook tasks are all addressed by this PR. Unittests and real tests (in my dev instance) are OK.
Now only the Discourse part remains to do.

**Comment by asaunier** [comment]
@arnaud-morvan Do you think we can merge this PR even though the Discourse part is not ready yet?
I would like to avoid leaving the PR open too long, which might create conflicts etc.
Thanks :)

**Comment by arnaud-morvan** [comment]
You have to rebase on master for https://github.com/c2corg/v6_api/pull/681/commits/de48c4872f25ab42b83dfe90ad93d75155495d62

**Comment by asaunier** [comment]
@arnaud-morvan Thanks for reviewing!
I have rebased the branch against master. Tests pass in my instance and I have also been able to merge 2 users successfully in my instance. Will merge when Travis gives the clearance.

**Pull request merged**
