### PR TITLE
[WIP] Add a default body to email messages

### PR DESCRIPTION
**Pull request by asaunier**
Else they are rejected by some email providers (eg. free.fr)

Related to https://github.com/c2corg/v6_api/issues/700

### CODE REVIEW

**Comment by asaunier** [comment]
Docker image of the current branch "email-body-attachement" has been pushed to the demo.

Here is an example of the email I have received after requesting a password reset:

capture du 2018-02-08 17-44-12

The first line ("FIXME: base email body") is the default email content introduced by this PR. If the suggested change works with free.fr addresses, we could change this test content to something more relevant.

@desnoes Could you please test with your free.fr address?
Testing with other email providers would make sense as well to make sure it is still OK with them.

**Comment by brunobesson** [comment]
As said on the mailing list, this does not seem entirely satisfying.
What about a solution distinguishing between the servers the mail is sent to?
AFAIU, we could do the following:

* attachment only for hotmail (which is the only case we have (?) with encoding problems)
* text only for others

**Comment by julsbreakdown** [comment]
@asaunier 
I've modified the code to its original state (before the hotmail fix).
It stills works with hotmail adresses, but this does not fixe the initial free problem.

**Comment by julsbreakdown** [comment]
Update : when changing SMTP server to gmail, mails sent to free adresses work.
So the problem seems to be with the SMTP server sparkpost.
In order to try to fix this problem, would it be possible to have access to the sparkpost server?
@stef74 @desnoes @asaunier

**Comment by stef74** [comment]
I need your mail to configure your account

2018-05-14 11:48 GMT+02:00 jwaddle <notifications@github.com>:

**Comment by julsbreakdown** [comment]
Here is mine julien.waddle@camptocamp.com could you also add arnaud.morvan@camptocamp.com

**Comment by stef74** [comment]
Invitation Sent !

2018-05-14 12:16 GMT+02:00 jwaddle <notifications@github.com>:

**Comment by asaunier** [comment]
Closing because replaced by https://github.com/c2corg/v6_api/pull/725

**Pull request closed without merging**
