### PR TITLE
Ensure to clear associations first?

### PR DESCRIPTION
**Pull request by brunobesson**
A fix for #1116?

Blind guess...

### CODE REVIEW

**Review by cbeauchesne — COMMENTED** [review]
Is there an unit test on this function? 

`blind guess` scares me a little :)

**Comment by brunobesson** [comment]
> Is there an unit test on this function?

There is. I thought I couldn't update it because there was already an association, but with a closer look today, there was an area association, not a map association. Let's see how it goes now.

**Comment by lbesson** [comment]
Blind guessing the unit tests 😁

**Comment by brunobesson** [comment]
@lbesson totally. Mind to fix it?

**Comment by brunobesson** [comment]
Please review.

**Review by cbeauchesne — APPROVED** [review]

**Review by lbesson — APPROVED** [review]

**Pull request merged**
