### PR TITLE
Add association history service

### PR DESCRIPTION
**Pull request by cbeauchesne**
## Todos

* [x] add sevice
* [x] add unit tests
* [x] unit tests genericity
* [x] request by user id
* [x] request without any parameter (whatsnew mode)
* [x] limit offset parameters 

## Won't dos
* Caching : any comment ? Is it often used ?

### CODE REVIEW

**Comment by asaunier** [comment]
@cbeauchesne I'll try to make a review when I have time (a bit later I'm afraid) with the limitation I'm getting a bit rusty with the API :P 
Thanks already for adding this very useful feature!

**Comment by cbeauchesne** [comment]
@brunobesson ok, sorry, I forgot that.

@asaunier thanks 🙏 I'll wait :)

**Comment by cbeauchesne** [comment]
Just added an index on AssociationLog columns child_document and parent_document (otherwise, the request takes around 250ms...). It now take 50ms with only one (big) query.

I've also limited the data requested.

**Comment by cbeauchesne** [comment]
Still WIP : after more thoughts, I think that this entry point could fit the what's new, and user contribution need. I'll add this asap today. 

* request by user id
* request without any parameter (whatsnew mode)
* limit offset parameters

**Comment by cbeauchesne** [comment]
ok, all yours. The service is generic. It accepts none, one or many parameters : 

* `d` for document_id
* `u` for userId
* `limit` 
* `offset`

It will be used for 

* get association history for a given document
* get associations made by one user
* follow associations, like whatsnew

**Comment by cbeauchesne** [comment]
Thank you very much @asaunier !

**Pull request merged**
