### PR TITLE
Add support for associations

### PR DESCRIPTION
**Pull request by tsauerwein**
* [x] Associations model
 * [x] Migrate associations
 * [x] Web-services to add/remove associations
 * [x] Return associations when requesting a document ([example resonse](http://pastebin.com/FZwrzDpc))
 * [x] Handle route names (see https://github.com/c2corg/v6_api/issues/120)
 * [ ] Handle geo-associations (see https://github.com/c2corg/v6_api/issues/128)
 * [ ] Show summit hierarchy
Example: http://www.camptocamp.org/summits/38641/fr/aiguille-du-peigne
c2corg-links

Closes https://github.com/c2corg/v6_api/issues/90
Closes https://github.com/c2corg/v6_api/issues/120

### CODE REVIEW

**Comment by tsauerwein** [comment]
I think this would be ready for a review. I haven't started with geo-associations yet, I would prefer to do that in a separate PR, so that this one does not grow to big.

**Comment by asaunier** [comment]
I will review the PR this afternoon I think.
Having a separated PR for geo associations makes sense.

**Comment by asaunier** [comment]
Looks good to me.

I have posted a few comments about the fact that the PR assumes (?) that WP and routes will be possibly associated for any document type (which I think is incorrect) but perhaps the behaviour could be change when adding other document types?

Concerning ES, it seems that only main WPs may be used to search for a route. Not any associated WP, which is really useful when you don't know what the main WP is or want to find all routes associated to a given WP. To do so we could not rely only on adding the associated WP names in the route titles in the ES index. This could be discussed in a separated issue, not preventing the current PR from being merged.

**Comment by tsauerwein** [comment]
Thanks for the review, Alex!

**Pull request merged**
