### PR TITLE
Change user category attribute

### PR DESCRIPTION
**Pull request by asaunier**
- User profiles may have several categories at a time
- Category "pro" is dropped and replaced by more detailed categories

Requires https://github.com/c2corg/v6_common/pull/8

### CODE REVIEW

**Comment by tsauerwein** [comment]
Here are two places where you still have to do the renaming:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/tests/__init__.py#L47-L58

Besides, looks good!

**Comment by asaunier** [comment]
Thanks @tsauerwein for pointing those 2 misses. There were still some others that I have also fixed :P 

I'm still struggling with this change because:

The tests fail since 
> File "/home/travis/build/c2corg/v6_api/c2corg_api/tests/views/test_user_profile.py", line 211
Lists differ: ['"mountain guide"'] != ['mountain guide']

I also have problems when running the migration:
> sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input value for enum guidebook.user_category: "i"
LINE 1: ...uring'] AS guidebook.activity_type[]), CAST(ARRAY['i', 'n', ...                                             ^
 [SQL: 'INSERT INTO guidebook.user_profiles (activities, categories, document_id) VALUES (CAST(%(activities)s AS guidebook.activity_type[]), CAST(%(categories)s AS guidebook.user_category[]), %(document_id)s)'] [parameters: {'activities': ['snow_ice_mixed', 'snowshoeing', 'ice_climbing', 'paragliding', 'mountain_climbing', 'rock_climbing', 'hiking', 'skitouring'], 'categories': ['i', 'n', 's', 't', 'i', 't', 'u', 't', 'i', 'o', 'n'], 'document_id': 2}]

It probably comes from https://github.com/c2corg/v6_api/blob/user-categories-pro/c2corg_api/scripts/migration/documents/user_profiles.py#L118-L120
=> "categories" is now a multi-select attributes (single-select in v5). I have also dropped the old category "pro" (id: 2). Are my changes appropriate?

**Comment by asaunier** [comment]
I think I have fixed the migration with
```
-            categories=self.convert_type(
-                document_in.category, MigrateUserProfiles.user_categories,
+            categories=self.convert_types(
+                [document_in.category], MigrateUserProfiles.user_categories,
```

Still the quotes problem with ``mountain guide``(added because of the middle space?)...

**Comment by tsauerwein** [comment]
About the migration script: The old field `category` was not a list, I guess you have to take that into account when calling `convert_types`.

> Still the quotes problem with mountain guide(added because of the middle space?)...

Can you try to replace the space with e.g. `_`?

**Comment by asaunier** [comment]
> About the migration script: The old field category was not a list, I guess you have to take that into account when calling convert_types.

Yes, that's why I have replaced ``document_in.category`` by ``[document_in.category]``. Does that look correct to you. At least the migration seems to work now, here is the result for my own profile:
```
                                               activities                                                | categories | document_id 
---------------------------------------------------------------------------------------------------------+------------+-------------
 {skitouring,rock_climbing,hiking,snowshoeing,snow_ice_mixed,ice_climbing,paragliding,mountain_climbing} | {amateur}  |         377
```

> Can you try to replace the space with e.g. _?

Done both in the tests and in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L595-L606 => the tests pass. Should I do the replacement?

**Comment by tsauerwein** [comment]
> Yes, that's why I have replaced document_in.category by [document_in.category]. Does that look correct to you? 

Sorry, missed that. You could add a check to avoid calling `convert_types` with `[None]`, but it will also work like that.

> Done both in the tests and in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L595-L606 => the tests pass. Should I do the replacement?

For all categories? If so that looks good.

**Comment by asaunier** [comment]
> You could add a check to avoid calling convert_types with [None]

OK I have done it: https://github.com/c2corg/v6_api/blob/user-categories-pro/c2corg_api/scripts/migration/documents/user_profiles.py#L108-L109

Travis still fails about some WP tests, I don't really see the connection.

**Comment by tsauerwein** [comment]
> Travis still fails about some route tests, I don't really see the connection.

These problems should be resolved once the outings PR is merged:
https://github.com/c2corg/v6_api/commit/ee94a0b001b93112e6da1ee6c862f6e5bbe344a1

**Comment by asaunier** [comment]
> These problems should be resolved once the outings PR is merged:

OK, at least Travis passes now :)

**Comment by asaunier** [comment]
Any objection against merging the PR?

**Comment by tsauerwein** [comment]
No, go for it. :)

**Comment by asaunier** [comment]
Thanks @tsauerwein

**Pull request merged**
