### PR TITLE
Geo-associations

### PR DESCRIPTION
**Pull request by tsauerwein**
This PR deals with geo-associations, the associations between maps, areas/regions and documents:

 * Adds the model classes for maps and areas, updates the migration script and adds web-services
 * The associations between maps and documents are not persisted. When requesting a document, the relevant maps are retrieved with a spatial query.
 * On the contrary, the associations between areas and documents are persisted in a table `area_associations`, because this information is needed also in listings. This table is updated when a new area or document is added, or the geometry of an area or document is updated.
 * Maps and associations are returned when requesting a single document.

TODO

 * [x] Include areas in listing views
 * [x] Everybody can edit title and description of an area, currently the geometry should not be editable. (-> only moderators can edit geometries)
 * [x] Currently no new areas can be created ( -> limited to moderators).

See https://github.com/c2corg/v6_api/issues/128

### CODE REVIEW

**Comment by tsauerwein** [comment]
I forgot to include the areas in listing views. But besides it's ready to review.

**Comment by asaunier** [comment]
Thanks for the huge and nice work!
As far as I can see, it looks good.

**Comment by tsauerwein** [comment]
Ok, this should be ready. Areas can now only be created by moderators. Everybody can update an area, but only moderators can change the geometry of an area. Even if we don't let moderators update an area in the UI, at least it is supported by the API.

**Comment by asaunier** [comment]
Cool, thanks a lot!
Looks good to me.

What about geoassociations of documents lacking their own geometry (for instance routes with no GPS track)?
Do they inherit the geoassociations from the associated documents (like in v5)? Note sure I have seen such a behaviour in the PR.
Or will we compute the geoassociations using an "inherited" default geometry from associated docs (as suggested in https://github.com/c2corg/v6_api/issues/128)? Do you think this is realistic?

When migrating v5 geoassociations do you also migrate those of geom-lacking docs?

**Comment by tsauerwein** [comment]
> What about geoassociations of documents lacking their own geometry (for instance routes with no GPS track)?

This PR does not deal with that. I opened a new issue for that: https://github.com/c2corg/v6_api/issues/144

**Comment by tsauerwein** [comment]
Ok for merging?

**Comment by asaunier** [comment]
Please do :+1:

**Comment by tsauerwein** [comment]
Thanks!

**Pull request merged**
