### PR TITLE
Change included associations for waypoints

### PR DESCRIPTION
**Pull request by tsauerwein**
* Rename waypoints_parents to waypoints
* Show routes directly associated to a waypoint first

closes https://github.com/c2corg/v6_api/issues/301

### CODE REVIEW

**Comment by asaunier** [comment]
Is the ``priority`` attribute used on the UI side? Or only on the API side to sort the directly associated routes first?

**Comment by tsauerwein** [comment]
> Is the priority attribute used on the UI side? Or only on the API side to sort the directly associated routes first?

It is only used in the SQL query to sort. It is not even returned.

**Comment by asaunier** [comment]
OK, looks good to me.

**Comment by tsauerwein** [comment]
Thanks for the review.

**Pull request merged**
