### PR TITLE
Merge alembic heads

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@asaunier : this should fix travis on v6_ui

**Comment by asaunier** [comment]
Thanks @arnaud-morvan !
Do we really need to add a new alembic script for this. Isn't this change enough: https://github.com/c2corg/v6_api/pull/703

**Comment by arnaud-morvan** [comment]
Yes, changing the downversion of one migration it is enough, I don't mind about one or the other.

**Comment by arnaud-morvan** [comment]
The merge should work for the ones who have already executed one of them.

**Comment by asaunier** [comment]
OK, since the other PR is merged, I guess the current one is not needed then?

> The merge should work for the ones who have already executed one of them.

I think no one has run the alembic scripts again except Travis.

**Comment by arnaud-morvan** [comment]
If the other one has been merged, this one is invalid now.

**Pull request closed without merging**
