### PR TITLE
Add missing search fields

### PR DESCRIPTION
**Pull request by tsauerwein**
See https://github.com/c2corg/v6_api/issues/311

### CODE REVIEW

**Comment by asaunier** [comment]
LGTM

Concerning the ``has_phone`` field https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/waypoint_mapping.py#L21-L22 => where have you seen it was needed? It seems weird to me to look for WP (even huts) that have a phone...

**Comment by tsauerwein** [comment]
> Concerning the has_phone field ... => where have you seen it was needed?

I am waiting on a confirmation that it can be removed.

**Comment by besson-genostar** [comment]
I agree with @asaunier this field feels nonsense to me for a search.

**Comment by asaunier** [comment]
> I am waiting on a confirmation that it can be removed.

I think you can remove it without further confirmation :)

**Comment by tsauerwein** [comment]
From https://github.com/c2corg/v6_api/issues/313#issuecomment-227711310:

> For outings, it seems that the "awesomeness" attribute will be removed => no need to take it into account.

So can I remove that field as well?

**Comment by asaunier** [comment]
> So can I remove that field as well?

Yes

**Pull request merged**
