### PR TITLE
Warning count from 1932 to 1842

### PR DESCRIPTION
**Pull request by cbeauchesne**
See #1133 for more details

### CODE REVIEW

**Comment by cbeauchesne** [comment]
@tsauerwein by chance, would it possible to have your opinion about this change : https://github.com/c2corg/v6_api/pull/1134/files#diff-bcdcacbeeac9f27f3ad65cda8f9decaee8aa8358a2cc6bf4709d821a2ccd637aR82 

I added it because we have a warning saying  `The Redis backend thread_local_lock parameter should be set to False when distributed_lock is True` > https://github.com/sqlalchemy/dogpile.cache/blob/master/dogpile/cache/backends/redis.py#L108 

Do you know if there any side-effect with this parameter ?

**Comment by lbesson** [comment]
I think that comes from one of the (outdated) dependencies. We already have this warning in the master branch and that still works.

**Comment by tsauerwein** [comment]
> @tsauerwein by chance, would it possible to have your opinion about this change : https://github.com/c2corg/v6_api/pull/1134/files#diff-bcdcacbeeac9f27f3ad65cda8f9decaee8aa8358a2cc6bf4709d821a2ccd637aR82
> 
> I added it because we have a warning saying `The Redis backend thread_local_lock parameter should be set to False when distributed_lock is True` : https://github.com/sqlalchemy/dogpile.cache/blob/master/dogpile/cache/backends/redis.py#L108
> 
> But I have absolutely no idea of its purpose, and it scares me a little bit :)
> 
> Do you know if there any side-effect with this parameter ?

Checking the [dogpile.cache documentation](https://dogpilecache.sqlalchemy.org/en/latest/api.html#dogpile.cache.backends.redis.RedisBackend), your change makes sense. The configuration uses `distributed_lock=True` because the API runs in multiple processes/containers/servers and the lock should be synchronized across all. As I understand it, `distributed_lock` and `thread_local_lock` are mutually exclusive. So it would make sense to set  `thread_local_lock` to `False`.

**Review by lbesson — APPROVED** [review]
don't want to update bbcode while you're at it? :D

**Comment by cbeauchesne** [comment]
@lbesson I've a loooooong todo list on API. I'm focusing on the easy one, and on ones that makes dev's life easier, sort of getting a foot in the door in a way :)

**Pull request merged**
