### PR TITLE
Add language parameter to document list service

### PR DESCRIPTION
**Pull request by tsauerwein**
The preferred language can be given with `/waypoints?l=fr`.

### CODE REVIEW

**Comment by tsauerwein** [comment]
I will also do the same for the search service.

**Comment by asaunier** [comment]
> The preferred language can be given with /waypoints?l=fr

Just wondering if it would not be more consistent to use ``lang=fr`` instead of ``l=fr``?

**Comment by asaunier** [comment]
Else looks good to me.

**Comment by gberaudo** [comment]
Is there a possibility to return an array of the available langs so that the client knows which ones he can request?

**Comment by tsauerwein** [comment]
> Just wondering if it would not be more consistent to use lang=fr instead of l=fr?

Currently the URL to get a waypoint is `/waypoints/1?l=en`. It would be nicer to use `/waypoints/1/fr` and `/waypoints/fr`, but we would have to define the Cornice resources differently. I can open an issue for that.

**Comment by tsauerwein** [comment]
> Is there a possibility to return an array of the available langs so that the client knows which ones he can request?

There is this property "available_cultures" which should be set all (?) views.

**Comment by asaunier** [comment]
> Currently the URL to get a waypoint is /waypoints/1?l=en. It would be nicer to use /waypoints/1/fr and /waypoints/fr, but we would have to define the Cornice resources differently.

Indeed. In the meantime I was just wondering if we should not used "lang" instead of "l" as lang parameter in API requests? Is there a reason for using "l"?

**Comment by tsauerwein** [comment]
> Is there a reason for using "l"?

It's short. ;)

**Comment by asaunier** [comment]
OK :)
Just asking because we use ``culture/lang/l" whereas we could simply use "lang" everywhere without having to wonder what is the correct parameter name :P

**Comment by tsauerwein** [comment]
I added a note to https://github.com/c2corg/v6_api/issues/101.

**Comment by asaunier** [comment]
> The preferred language can be given with /waypoints?l=fr.

Just to make sure I get it well: on the UI side, you send a ``/waypoints?l=<lang>`` request with ``<lang>``being the user's interface language. The API sends back a list of waypoint preferably with the ``<lang>`` locale, if the latter is not available it uses the next available locale in the lang priority list. Right?

**Comment by tsauerwein** [comment]
Yes, right. Each document returned by `/waypoints?l=...` contains exactly one locale.

**Comment by gberaudo** [comment]
It would be better to use something else than  `l` or `lang`, since the returned locale is not the one in parameter but the `best` one. It will help avoid confusion. What about something like `bestlang`?

**Comment by asaunier** [comment]
@gberaudo 's objection makes sense. For the sake of simplicity and shortness, ``l`` (or later ``lang``) is OK for me but we could use ``pref_lang`` (since "best" is confusing :P).

**Comment by tsauerwein** [comment]
> OK for me but we could use pref_lang (since "best" is confusing :P).

I am not really fan of these heavy names for GET parameters. I don't think that this is a problem if we document it in our not yet existing API documentation.

**Comment by tsauerwein** [comment]
I pushed one more commit doing the same for the search web-service. Same for https://github.com/c2corg/v6_ui/pull/73

**Comment by gberaudo** [comment]
Even if documented, the parameter is ambigous`and will cause confusion.

It also conflicts with a potential parameter for retrieving the document `in` a specific language.
It would be wise to keep `l/lang` for this later use case.

I am fine with `pref_lang` as proposed by @asaunier; it is "heavy" but it is an API-only parameter.
All that being said, I don't want to block the PR so feel free to do as you think best.

**Comment by tsauerwein** [comment]
> Even if documented, the parameter is ambigous`and will cause confusion.
> 
> It also conflicts with a potential parameter for retrieving the document in a specific language.
> It would be wise to keep l/lang for this later use case.
> 
> I am fine with pref_lang as proposed by @asaunier; it is "heavy" but it is an API-only parameter.

I changed it to `?pl=..`, short but still different to `?l=..`.

**Comment by gberaudo** [comment]
Great thanks @tsauerwein.

**Pull request merged**
