### PR TITLE
Allow * in CORS

### PR DESCRIPTION
**Pull request by gberaudo**
CORS * allows any web client to send requests to the API.
The API will check for the token so:
- browsers sending an authorization token will get access to protected
  content;
- browsers not sending an authorization token will only get access to
  public content.

There is no security reason to maintain and restrict access to some
whitelisted domains.

When using cookies together with a CSRF token, the situation is
identical and using * is also secure.

### CODE REVIEW

**Comment by gberaudo** [comment]
See discussion in #111.

**Comment by tsauerwein** [comment]
Sounds good for me.

**Comment by asaunier** [comment]
OK then. Thanks for cleaning the code.

**Comment by gberaudo** [comment]
Thanks for the review.

**Pull request merged**
