### PR TITLE
Add basic user migration from v5

### PR DESCRIPTION
**Pull request by gberaudo**
25 users are duplicated in v5 (same login_name).
A suffix is added to the oldest user.

### CODE REVIEW

**Comment by tsauerwein** [comment]
That's looking good! Can you also update the sequence for the user id, like here:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/sequences.py

**Comment by gberaudo** [comment]
Updated.
@tsauerwein, do you know why Travis fails?

**Comment by tsauerwein** [comment]
Mhm no, tests pass locally.

**Comment by gberaudo** [comment]
Found the issue and updated the PR.

**Comment by gberaudo** [comment]
Thanks for the review @tsauerwein.

**Pull request merged**
