### PR TITLE
Add user profile

### PR DESCRIPTION
**Pull request by tsauerwein**
TODO:

* [x] Create user profile when creating user
* [x] Adapt migration script

### CODE REVIEW

**Comment by tsauerwein** [comment]
Ready to review

**Comment by asaunier** [comment]
Looks good to me, thanks!

Concerning the migration of the user profiles, I will ask the association if the "pro" category is really relevant. I don't think so since pros could be mountain guides, mountain leaders ("accompagnateurs en montagne"), ski instructors, climbing instructors, etc. => category "pro" is too wide to be useful. In addition we probably need a category for hut wardens. But no need to bother about that now.

Concerning the "profileless" users, just curious what this means: do we really have accounts with no profile?

**Comment by tsauerwein** [comment]
> Concerning the "profileless" users, just curious what this means: do we really have accounts with no profile?

Yes, these four: 110471, 110473, 112744, 112745

**Comment by tsauerwein** [comment]
Thanks for the review!

**Comment by asaunier** [comment]
Another question: I guess that as for other document types, the user profile "title" is edited directly in the document (creating a new archive version etc.), right?

Maybe it's OK, however please note that in v5 the "profile" title (aka "topoguide name") is updated using a different "user account settings" interface where the user may change his "topoguide name" as well as his "forum name", email address, password etc.

**Comment by tsauerwein** [comment]
> Maybe it's OK, however please note that in v5 the "profile" title (aka "topoguide name") is updated using a different "user account settings" interface where the user may change his "topoguide name" as well as his "forum name", email address, password etc.

Ok, I see. I think it makes things too complicated to use the profile title as "guidebook name". We should add a new field to the user model for that.

**Comment by asaunier** [comment]
Can't we ignore the userprofile's title (by simply not showing it in the profile page nor in the editing page) and display the user's "guidebook name" instead?

**Pull request merged**
