### PR TITLE
Use more consistent document_id in user association requests

### PR DESCRIPTION
**Pull request by asaunier**
See https://github.com/c2corg/v6_ui/issues/619#issuecomment-247615305

### CODE REVIEW

**Comment by tsauerwein** [comment]
You didn't have to update any tests?

**Comment by asaunier** [comment]
Indeed. I'm having a look.

**Comment by asaunier** [comment]
I have made changes in the tests but I'm afraid it's not enough.

**Comment by tsauerwein** [comment]
Here: https://github.com/c2corg/v6_api/blob/16146864d0b996b5b8f34d32ce8c4a5152960d13/c2corg_api/views/validation.py#L263

This can now be:

    'document_id': doc['document_id'],

**Comment by asaunier** [comment]
Thanks, updated. But still plenty of errors :P

**Comment by tsauerwein** [comment]
> ... still plenty of errors

Travis passes? Your changes look good to me, feel free to merge if you think it is ready.

**Comment by asaunier** [comment]
Indeed the tests also pass in my instance (?). Thanks for the review. Merging.

**Pull request merged**
