### PR TITLE
Use custom schema for each waypoint type

### LINKED ISSUE #37: Returning a document for a single culture
When displaying a document, in most cases it is no use retrieving all cultures, since only one is displayed.

As for now the API returns all available cultures for a given document call.
It would be useful to be able to specify the desired culture.

### PR DESCRIPTION
**Pull request by tsauerwein**
... so that only the fields specific for a waypoint type are returned.

Also adds the column `available_cultures`.

Closes #37

### CODE REVIEW

**Comment by asaunier** [comment]
"available_cultures" => a field that is only available in the main doc table, not in the archives, right? The info is then available only in one place per document. Looks good.

**Comment by tsauerwein** [comment]
> "available_cultures" => a field that is only available in the main doc table, not in the archives, right?

Yes exactly. This field is not stored in the database. It is simply set before creating the JSON:
https://github.com/c2corg/v6_api/commit/4dd7a6ae694f90d1bf06fd13507dd5680df6fdc2#diff-b906af94797c5db6c394971ac60bf7a4R31

**Comment by asaunier** [comment]
OK. Would it be relevent to store it in the documents table in order to avoid the query used to fill this attribute?

**Comment by tsauerwein** [comment]
When we would store it in the database, we would have to make sure that this field is updated every time a locale is added/removed.

Also note that only a single query is made when requesting a list of documents. I don't think this additional query is a performance issue. Especially once we are enabling the cache.

**Comment by asaunier** [comment]
OK it makes sense.
From my perspective, it's OK to merge this PR.

**Comment by tsauerwein** [comment]
Thanks!

**Pull request merged**
