### PR TITLE
Use consistent attributes

### PR DESCRIPTION
**Pull request by tsauerwein**
... for the simple search, advanced search and associated document in detail pages.

The big advantage, beside the consistency and the simpler code, is that all different services use the same cache. For example if the simple search returns a document, this document will be cached. If the document is returned again in the advanced search or as association, it can directly be loaded from the cache.

The responses from the API have changed in some places:

- Users in outings now have their id as `document_id` instead of `id` (closes https://github.com/c2corg/v6_api/issues/321)
- Route associations for waypoints no longer include `geometry_detail`
- The structure for `recent_outings` has been changed from `'recent_outings': {'outings': ...}}` to  `'recent_outings': {'documents': ...}}` (same for `all_routes`). 

TODO

* [x] I still want to optimize the query to get the documents to only include the attributes  that are needed. But I would like to this in a separate PR.

Closes https://github.com/c2corg/v6_api/issues/348
Closes https://github.com/c2corg/v6_api/issues/300
Closes https://github.com/c2corg/v6_api/issues/192
Closes https://github.com/c2corg/v6_api/issues/93

### CODE REVIEW

**Comment by asaunier** [comment]
Is this PR still WIP? Let us know when you need a review.

> The responses from the API have changed in some places:

Those changes probably requires several adaptations in the UI. Perhaps we should wait alpha3 is released before merging the PR and do the changes in the UI?

**Comment by tsauerwein** [comment]
> Is this PR still WIP? Let us know when you need a review.

No, it's ready to review. Probably you want to review commit-by-commit, because I did some heavy refactorings.

> Perhaps we should wait alpha3 is released before merging the PR and do the changes in the UI?

Ok for me.

**Comment by tsauerwein** [comment]
> I still want to optimize the query to get the documents to only include the attributes that are needed. But I would like to this in a separate PR.

I have done it in this PR. Please review.

**Comment by asaunier** [comment]
I will take a look soon.

**Comment by asaunier** [comment]
It seems your last commit 6a388b8 breaks the test.
Else the PR looks good to me.

I have created a UI issue for listing the changes we will have to make in the UI when the PR is merged: https://github.com/c2corg/v6_ui/issues/619
Can you think of other changes that will have to be done?

**Comment by tsauerwein** [comment]
Thanks for your review!

I forgot to update the common project, the tests should now pass.

> Can you think of other changes that will have to be done?

No, I think I listed all points that have changed above.

**Comment by tsauerwein** [comment]
@dkocich Now that this PR is merged, you could rebase your branch on the current master.

**Pull request merged**
