### PR TITLE
Introduce base class for testing views

### PR DESCRIPTION
**Pull request by gberaudo**
Introduce a base class for testing views and factorize basics test methods.

Used by:
- [X] images;
- [x] routes;
- [x] waypoints

### CODE REVIEW

**Comment by gberaudo** [comment]
Related to https://github.com/c2corg/v6_api/pull/23#issuecomment-144013963.
@tsauerwein, @asaunier, could you please review the change? I will then update the routes and waypoint test files.

**Comment by tsauerwein** [comment]
Looks ok

**Comment by tsauerwein** [comment]
Thanks for refactoring this, Guillaume! Feel free to merge when you think it is ready. I will base my versioning branch on it.

**Comment by gberaudo** [comment]
Thank you for the review @tsauerwein.

**Pull request merged**
