### PR TITLE
Fix web-service to get version of a document

### PR DESCRIPTION
**Pull request by tsauerwein**
Now for real.

### CODE REVIEW

**Comment by asaunier** [comment]
:+1:

**Comment by gberaudo** [comment]
@tsauerwein, isn't it better to request only the data we will actually send to the client? I am wondering what is the performance implication of using the ORM.
Retrieving the archived documents takes three requests to the database. Wouldn't it work with a join?

**Comment by tsauerwein** [comment]
I changed the the four queries into a huge query. I am wondering if that is better performance-wise.

Anyway, I am not particularly worried about the performance for this web-service, because I don't think it will be called that often.

> isn't it better to request only the data we will actually send to the client?

To load only specific columns we could use [load_only](http://docs.sqlalchemy.org/en/latest/orm/loading_columns.html#load-only-cols).

**Comment by gberaudo** [comment]
Looks great to me, thanks.

**Comment by tsauerwein** [comment]
Thanks for the review.

**Pull request merged**
