### PR TITLE
[WIP] Add doc. types and lang. filters to /whatsnew feed on API

### PR DESCRIPTION
**Pull request by dkocich**
http://localhost:6548/documents/changes?u=113594&t=c,x&lang=de should work now

### CODE REVIEW

**Comment by cbeauchesne** [comment]
@dkocich, @asaunier, do you remember why this PR has not been merged ?

**Comment by asaunier** [comment]
Sorry, I don't remember.

**Comment by dkocich** [comment]
hello, I guess that I was leaving CtC around the end of Feb 2017 and other tasks had priority for the rest of our team / no one took it over to finish it?

**Comment by cbeauchesne** [comment]
Ok, thank you. I'll seee how to finish this, once we have finished my work on the dev env.

**Comment by dkocich** [comment]
Ok, there was also FE part prepared https://github.com/c2corg/v6_ui/pull/1524 which you have to adapt...

**Pull request closed without merging**
