### PR TITLE
Ignore merged documents in the ES indexing script

### PR DESCRIPTION
**Pull request by asaunier**
Related to https://github.com/c2corg/v6_api/issues/710

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
Could be rebased now

**Comment by asaunier** [comment]
> Could be rebased now

Thanks, done!

**Comment by asaunier** [comment]
@arnaud-morvan Thanks for the approval. I am waiting for Travis to pass and generate the docker image. Then I will push the image to the demo and have it tested before it is merged. We have to make sure the changes does not impact the syncer.

**Comment by arnaud-morvan** [comment]
Regarding your diff, it should not alter syncer behavior.

**Pull request merged**
