### PR TITLE
Improve search

### PR DESCRIPTION
**Pull request by tsauerwein**
- Only search on the title for the simple search.
- Use an analyzer that is more adapted to place or user names.
- Boost the fields for the given language.
- Fixes a problem with elision filters (e.g. "l'article" -> "article").

All the problems mentioned in https://github.com/c2corg/v6_api/issues/206 are fixed with these improvements.

Related to https://github.com/c2corg/v6_api/issues/206
Related to https://github.com/c2corg/v6_ui/issues/493
Related to https://github.com/c2corg/v6_ui/issues/351

### CODE REVIEW

**Comment by asaunier** [comment]
Thanks!
I would prefer the related issues are not autoclosed when the PR is merged. So that the client or myself may test all problems are actually fixed.
Does this PR require to run the ES indexing script before it can be tested?

**Comment by tsauerwein** [comment]
> Does this PR require to run the ES indexing script before it can be tested?

Yes, the index has to be re-created.

**Comment by asaunier** [comment]
Arf, that's pretty long to recreate the index on the dev server so I prefer to test when the PR is merged :P
Could you edit your initial comment so that the issues are not autoclosed? I will mark them as "fixed and ready to be tested".

**Comment by asaunier** [comment]
Oops, forget it. I though that "closes" autoclosed the issues when the PR is merged. But it does not.

**Comment by tsauerwein** [comment]
> Oops, forget it. I though that "closes" autoclosed the issues when the PR is merged. But it does not.

It does. I changed it to "relates to".

**Comment by stef74** [comment]
@tsauerwein this PR is on demo or not ?

**Comment by tsauerwein** [comment]
It is.

**Pull request merged**
