### PR TITLE
Image fixes

### PR DESCRIPTION
**Pull request by gberaudo**
- [X] Add filename to image listing;
- [ ] Return image associations (in another PR).

### CODE REVIEW

**Comment by tsauerwein** [comment]
> Return image associations

I am currently doing some profound changes to this part (https://github.com/c2corg/v6_api/tree/associations-edit), so you might want to wait until I am done to avoid an ugly rebase. Or I can do it as part of my work.

**Comment by gberaudo** [comment]
Thanks @tsauerwein for notifying me. If you want to do it please go on, otherwise I will do it after you merge your changes.

**Comment by gberaudo** [comment]
@tsauerwein I fixed the test. If it is OK with you I will merge the PR with only the first item done.

**Comment by tsauerwein** [comment]
Sure!

**Comment by gberaudo** [comment]
Thanks

**Pull request merged**
