### PR TITLE
Handle merged documents

### PR DESCRIPTION
**Pull request by tsauerwein**
Closes https://github.com/c2corg/v6_api/issues/185

Still to do:

* [x] Do not index in ES
* [x] Ignore when returned as ES search result
* [x] Do not migrate merged documents

### CODE REVIEW

**Comment by asaunier** [comment]
The changes about the areas sure make sense. Please note though that since it is not possible (at least in v5) to create areas, we never have to merge areas.

**Comment by tsauerwein** [comment]
> Please note though that since it is not possible (at least in v5) to create areas, we never have to merge areas.

I did it for all document types to be consistent.

**Comment by asaunier** [comment]
Yep, you did well. That was just to precise what actually happens with the areas.

**Comment by tsauerwein** [comment]
Ready to review

**Comment by asaunier** [comment]
Looks good to me, thanks!

**Pull request merged**
