### PR TITLE
Have distinct routes for waypoint results (one more try, DISTINCT is not enough)

### PR DESCRIPTION
**Pull request by brunobesson**
Looks like returned routes of a waypoint still have duplicates

### CODE REVIEW

**Comment by brunobesson** [comment]
Ok, I think I get the issue: to sort routes by waypoint priority (direct waypoint, then children waypoint, then grandchildren waypoints), the request make a join on the waypoint. If routes are associated to several of these waypoints, we get several rows with same route id, but different associated waypoint.

To distinguish thoses, I had to remove this sort and use DISTINCT ON (route.document_id) rather than a simple DISTINCT.

So we win no-dup routes, but loose the ordering based on associated waypoints. As in paralell we aim at no limiting the number of results returned, except for exceptional or buggy cases (except Calanques waypoint, we never have over 300 associated routes and aim at using a limit of 300 or 400), I do think we can do so, unless someone knows how to solve this best.

What do you think?

**Comment by brunobesson** [comment]
This would fix #589 remaining issue.

**Comment by lbesson** [comment]
imho ordering a few docs in the UI is manageable, since it's not dynamic (but maybe I don't know vue enough on that)

**Comment by brunobesson** [comment]
The problem is not ordering results, but filtering.

Without this fix, API is supposed to return 30 results, but there may be some duplicates within. So the frontend has to filter this (which it does, currently). In addition to this useless hassle, you do not present 30 results, but only a fraction of it. In worst case scenarios, you may have less than half of the results.

P.S. : I am already working on a PR on the frontend side to sort results, that's not a problem.

**Review by cbeauchesne — APPROVED** [review]
Well, I do not have any knowledge with SQL Alch. so, I won't be a great help here. 

Sorry for stating the obvious, but I guess you did exhaustive tests on it? ;) 

For my own curiosity, what was the purpose of `literal_column('1').label('priority'))` lines, and why is not not necessary anymore?

**Comment by brunobesson** [comment]
It is used to order results based on the waypoint 'proximity' to the main waypoint : retrieve first routes associated to the main waypoint, then children waypoint then grandchildren ones.
To me it is ok to loose this sort of we augment the number of routes retrieved from 30 to e.g. 400 as proposed. Because only in exceptional circumstances would this sort be useful. And 'big' waypoints such as Calanques or Verdon or Aiguilles de Cham should not have routes directly attached to this main waypoint.

**Pull request merged**
