### PR TITLE
Update cache keys when areas or maps change

### PR DESCRIPTION
**Pull request by tsauerwein**
When a map or area changes, the cache keys of associated documents have to be updated.

Associations between maps and documents are now also stored in a table (same as for areas), because maps do not change that often.

Closes https://github.com/c2corg/v6_api/issues/362

The migration script has to be run again, because changes to the database were made.

### CODE REVIEW

**Comment by asaunier** [comment]
LGTM

> The migration script has to be run again, because changes to the database were made.

Should we run the migration script from scratch in the demo DB or could I simply apply the SQL commands found in https://github.com/c2corg/v6_api/pull/367/files ?

**Comment by tsauerwein** [comment]
There also is a new table, which is filled during the migration.

**Comment by asaunier** [comment]
So it means a full migration is needed?!
Can we wait that https://github.com/c2corg/v6_api/issues/363 is fixed before reimporting the DB?

**Comment by tsauerwein** [comment]
Sure, I can wait with merging this PR.

**Comment by tsauerwein** [comment]
I am merging now, because some changes are required for https://github.com/c2corg/v6_api/pull/340.

**Pull request merged**
