### PR TITLE
WIP Image fields

### PR DESCRIPTION
**Pull request by ginold**

### CODE REVIEW

**Comment by asaunier** [comment]
Is this PR still valid?

**Comment by ginold** [comment]
no :)

**Comment by ginold** [comment]
Or yes, I think I do need it! It adds the missing values that are not returned for Images from the API.

**Comment by tsauerwein** [comment]
> Or yes, I think I do need it! It adds the missing values that are not returned for Images from the API.

Please rebase.

**Comment by ginold** [comment]
In the meantime, i noticed that c2corg_api/models/association.py has completely changed, the modified functions are not in the same file and I don't know if rebasing will be of any help. Or will it?

**Comment by tsauerwein** [comment]
During the rebase you will have to adapt your previous changes to the current code.

**Comment by asaunier** [comment]
Perhaps it's easier to close the PR and to make a new one from HEAD?

**Comment by ginold** [comment]
exactly my thought

**Comment by asaunier** [comment]
Don't forget to delete the branch then.

**Pull request closed without merging**
