### PR TITLE
Add size param to image proxy view

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Relate https://github.com/c2corg/v6_ui/issues/712

### CODE REVIEW

**Comment by asaunier** [comment]
Are query string params like ``?size=BI`` in ``/images/proxy/5555?size=BI`` correctly taken into account by Varnish? Wouldn't it better to use `` /images/proxy/5555/BI``?

**Comment by tsauerwein** [comment]
> Are query string params like ?size=BI in /images/proxy/5555?size=BI correctly taken into account by Varnish (ie. cached)? Wouldn't it better to use /images/proxy/5555/BI?

That does not make a difference for Varnish.

**Comment by tsauerwein** [comment]
@arnaud-morvan Please fix the linter errors, and then feel free to merge.

**Comment by asaunier** [comment]
Is there still something preventing this PR from merging?

**Comment by arnaud-morvan** [comment]
If it's ok for the UI point of view, we can merge

**Pull request merged**
