### PR TITLE
Add all fields for waypoints

### PR DESCRIPTION
**Pull request by tsauerwein**
Still to do:

- [x] Add class `WaypointGeometry` with a field for an additional geometry (e.g. for lakes, cliffs, ...).
- [x] Add validation for each waypoint type (e.g. type `summit` requires the fields a, b, ...).

### CODE REVIEW

**Comment by asaunier** [comment]
I don't know if you plan to do it in this branch, but we have to change the "activity" behaviour for routes (OK it's not waypoints :P ) since a route (resp. outing/image/article/...) may have several activities at the same time. As for now only one at a time may be picked.

**Comment by tsauerwein** [comment]
> I don't know if you plan to do it in this branch, but we have to change the "activity" behaviour for routes (OK it's not waypoints :P ) since a route (resp. outing/image/article/...) may have several activities at the same time. As for now only one at a time may be picked.

I noticed this. I think we can do that when we add the fields for routes.

**Comment by asaunier** [comment]
OK I have added an issue about that point https://github.com/c2corg/v6_api/issues/45

**Comment by asaunier** [comment]
What about renaming waypoint_type to simply type?
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L21

**Comment by elemoine** [comment]
> What about renaming waypoint_type to simply type?
> https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L21

The reason of using `waypoint_type` as a name may be related to `type` being a keyword of the Python language. `typ` is quite often used in Python projects.

**Comment by tsauerwein** [comment]
Ready for review

**Comment by asaunier** [comment]
I have only minor comments, looks like a good job!

What the purpose of the geom_detail attribute?

**Comment by tsauerwein** [comment]
`geom_detail`is for the field "Limite de l'objet".

**Comment by asaunier** [comment]
> geom_detailis for the field "Limite de l'objet".

Why do we need this?

**Comment by tsauerwein** [comment]
It's in the spec, for example to have an additional polygon for the shape of a lake, glacier or cliff.

**Comment by asaunier** [comment]
Arf... OK, but it sounds a bit complicated and I'm not sure editing such geometries is in the project perimeter anyway...

From my perspective it's OK to merge the PR.

**Comment by asaunier** [comment]
Are you still waiting for some review?
Would be cool if you could merge this PR soon, this way I won't have to recreate my DB several times :P

**Comment by tsauerwein** [comment]
Ok, ok, I am merging. :)

**Comment by asaunier** [comment]
There might be a problem with this PR. After updating/cleaning/installing my instance, I have tried to recreate the DB with scripts/create_user_db.sh but I got the following error:
```
CREATE DATABASE
You are now connected to database "c2corg_alex" as user "postgres".
CREATE EXTENSION
CREATE SCHEMA
Traceback (most recent call last):
  File ".build/venv/bin/initialize_c2corg_api_db", line 9, in <module>
    load_entry_point('c2corg-api==0.0', 'console_scripts', 'initialize_c2corg_api_db')()
  File "/home/alex/v6_api/.build/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/alex/v6_api/.build/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/home/alex/v6_api/.build/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/home/alex/v6_api/c2corg_api/__init__.py", line 4, in <module>
    from c2corg_api.models import (
  File "/home/alex/v6_api/c2corg_api/models/__init__.py", line 23, in <module>
    from c2corg_api.models import waypoint  # noqa
  File "/home/alex/v6_api/c2corg_api/models/waypoint.py", line 302, in <module>
    'geometry': geometry_schema_overrides
  File "/home/alex/v6_api/.build/venv/local/lib/python2.7/site-packages/colanderalchemy/schema.py", line 167, in __init__
    self.add_nodes(self.includes, self.excludes, self.overrides)
  File "/home/alex/v6_api/.build/venv/local/lib/python2.7/site-packages/colanderalchemy/schema.py", line 191, in add_nodes
    name_overrides_copy
  File "/home/alex/v6_api/.build/venv/local/lib/python2.7/site-packages/colanderalchemy/schema.py", line 335, in get_schema_from_column
    % (repr(column_type), name)
NotImplementedError: Not able to derive a colander type from sqlalchemy type: ArrayOfEnum(Enum('couenne', 'bloc', 'psicobloc', name='climbing_outdoor_type', schema='guidebook', metadata=MetaData(bind=None)))  Please explicitly provide a colander `typ` for the "climbing_outdoor_types" Column.
```

**Comment by tsauerwein** [comment]
Please make a `make -f ... install` to get the good version of ColanderAlchemy.

**Comment by asaunier** [comment]
I did a ``make -f ... clean install``...

I have just tried to make a ``make -f ... install``, with no more luck.

**Comment by asaunier** [comment]
When I run the install command I get this:
```
Downloading/unpacking git+https://github.com/tsauerwein/ColanderAlchemy.git@c2corg (from -r requirements.txt (line 6))
  Cloning https://github.com/tsauerwein/ColanderAlchemy.git (to c2corg) to /tmp/pip-c5xGuT-build
  Running setup.py (path:/tmp/pip-c5xGuT-build/setup.py) egg_info for package from git+https://github.com/tsauerwein/ColanderAlchemy.git@c2corg
    
  Requirement already satisfied (use --upgrade to upgrade): ColanderAlchemy==0.3.4.dev1 from git+https://github.com/tsauerwein/ColanderAlchemy.git@c2corg in ./.build/venv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Obtaining file:///home/alex/v6_api (from -r requirements.txt (line 8))
```

**Comment by tsauerwein** [comment]
Ok, please do:

     .build/venv/bin/pip uninstall ColanderAlchemy

and then again `make -f ... install`.

**Comment by asaunier** [comment]
Thanks, it works better :)

**Pull request merged**
