### PR TITLE
Obey convention for cornice errors

### PR DESCRIPTION
**Pull request by gberaudo**
See
http://cornice.readthedocs.org/en/latest/validation.html#dealing-with-errors

With errors being a JSON dictionary with the keys “location”, “name” and “description”.
- location is the location of the error. It can be “querystring”, “header” or “body”
- name is the eventual name of the value that caused problems
- description is a description of the problem encountered.

### CODE REVIEW

**Comment by tsauerwein** [comment]
Thanks! :)

**Comment by gberaudo** [comment]
@tsauerwein this PR also fixes other places where we did not obeyed the convention.
@asaunier, this change may require changes in the ui.

**Comment by asaunier** [comment]
> this change may require changes in the ui.

OK thanks, please merge, we'll then see what we have to change in the UI.

**Comment by gberaudo** [comment]
Thanks for the reviews.

**Pull request merged**
