### PR TITLE
Add a clear cache script

### PR DESCRIPTION
**Pull request by tsauerwein**
Closes https://github.com/c2corg/v6_api/issues/361

We still have to see with @mfournier how this script can be integrated in the deployment process, so that the cache is cleared when deploying a new version.

### CODE REVIEW

**Comment by asaunier** [comment]
Looks good to me.

Just a question: what happens if the wrong clear cache command is run. For instance ``clear-cache-prod`` in a dev instance or ``clear-cache`` in prod?
Since prod is the "real" application, wouldn't it make more sense that ``clear-cache`` is the prod command (``clear-cache-dev`` for the dev). Or ``clear-cache-prod``/``clear-cache-dev``?

**Comment by tsauerwein** [comment]
> Just a question: what happens if the wrong clear cache command is run. For instance clear-cache-prod in a dev instance or clear-cache in prod?

In the worst case, the cache entries have to be recreated on the next request.

> Since prod is the "real" application, wouldn't it make more sense that clear-cache is the prod command (clear-cache-dev for the dev). Or clear-cache-prod/clear-cache-dev?

I followed the naming schema that we used for other targets (run-syncer/run-syncer-prod or run-background-jobs/run-background-jobs-prod). I don't mind about the name. I let you change it in a separate PR if you do. :)

**Comment by asaunier** [comment]
OK if it's more consistent.
And it's probably "safer": if one runs the "clear-cache" command in prod it will not actually impact the prod cache, right? The explicit "clear-cache-prod" command is required.

**Comment by tsauerwein** [comment]
Actually it is more important which Makefile config you use.

On prod, you will use: `make -f config/main clear-cache-prod`.
On your test instance: `make -f config/alex clear-cache`.

But `make -f config/alex clear-cache` and `make -f config/alex clear-cache-prod` will clear the same Redis database. Because currently all dev configs share the same Redis db for dev and prod (with different cache keys so that the value do not get mixed up).

**Pull request merged**
