### PR TITLE
[WIP] Add chinese lang

### PR DESCRIPTION
**Pull request by cbeauchesne**
#856 and #1036

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Codacy issue: assert on test files ...

I didn't find how to ignore a given test on a folder => ignore this alert.

**Comment by lbesson** [comment]
within codacy, you can specify folders and files to be ignored
image

**Comment by lbesson** [comment]
You can also use python pragmas to ignore specific lines (# noqa)

**Comment by cbeauchesne** [comment]
I saw this, but it totally ignore the file. I'd like to ignore it only for this rule. But if you're ok, we can do this (I'm not a huge fan of codacy, I feel that the signal/noise ratio is terrible).

**Comment by lbesson** [comment]
the # noqa stuff should allow you to not completely ignore the file, doesn't it?

**Comment by cbeauchesne** [comment]
ready for your review @lbesson :)

**Comment by lbesson** [comment]
aren't we using zh_CN elsewhere in the code?
Except this, lgtm

**Review by lbesson — APPROVED** [review]

**Comment by cbeauchesne** [comment]
> aren't we using zh_CN elsewhere in the code?

In the UI yes.

I've been a little bit lazy here. The db columns for lang are 2 char wide, I'd to resize them, and changes some code to trim the result. 

As we have only one proposal for chinese, my plan is (including my laziness) : 

* On UI side, it's easy to have several one, and we're more likely to have one more translator
* map all of them on `zh`
* And if, one day, we'll have several people who are willing to moderate several chinese declinaison, I'll to the column resize.

**Pull request merged**
