### PR TITLE
Support merging documents

### PR DESCRIPTION
**Pull request by tsauerwein**
Still to do:

* [x] Delete files for images (requires https://github.com/c2corg/v6_images/issues/35)
* [x] Make sure no new associations can be created with redirected documents
* [x] Do not try to transfer an association if the association already exists with the target document

Not handled: Merging user accounts.

Related to https://github.com/c2corg/v6_api/issues/386

### CODE REVIEW

**Comment by asaunier** [comment]
Comments should probably be managed as well when a document is merged. Either by moving the comments to the target doc, or by removing them (needed when deleting a document as well).

**Comment by tsauerwein** [comment]
> Comments should probably be managed as well when a document is merged.

It would be possible to make a request to the Discourse API to move comments from one topic to another topic.

I am wondering what we should do if the source and target document do not have the same locales. E.g. the source document has a translation in English and German, and the target document translations in French and Spanish. How would you transfer the comments?

Maybe it's a rare case, and we could simply warn the moderator if it occurs. Otherwise we could let the moderators manually take care of merging the comments. What do you think?

**Comment by tsauerwein** [comment]
Besides the open question on how to handle comments, this PR would be ready to review.

**Comment by fjacon** [comment]
@tsauerwein  for now (V6.1), we do not take care of comments : we keep only comments from the target document.

**Comment by tsauerwein** [comment]
Thanks for the review!

**Pull request merged**
