### PR TITLE
Add support for outings

### PR DESCRIPTION
**Pull request by tsauerwein**
TODO

* [x] Include associated users in response
* [x] Make it possible to include associated users when creating an outing
* [x] Check that only associated users or moderators can edit an outing
* [x] Create associations for linked waypoint and route when creating an outing
* [x] Include associated outings for waypoints and routes (maybe the latest 10?)
* [x] Add new web-service to get all associated outings for a document (paginated, for [this page](http://www.camptocamp.org/outings/list/summits/41165/orderby/date/order/desc))
* [x] Check that associations between users and outings are migrated
* [x] Check if the association between outing and waypoint is needed (it seems in v5 there are no associations between outings and waypoints)

Requires #156

### CODE REVIEW

**Comment by tsauerwein** [comment]
Ready to review

**Comment by asaunier** [comment]
> Include recent outings for waypoints

Nice!

> Add params to get outings for waypoint/route

How does it work? That's to show the full list of outings for a given route or WP (complementy the last 10 outings that are shown in route or WP pages)?

**Comment by asaunier** [comment]
Oops: I forgot to say: nice work, looks good to me :)

**Comment by tsauerwein** [comment]
> How does it work? That's to show the full list of outings for a given route or WP (complementy the last 10 outings that are shown in route or WP pages)?

Yes. Like this:

`/outings?wp=37355` or `/outings?r=46096`

**Comment by asaunier** [comment]
Cool!

**Comment by tsauerwein** [comment]
Thanks

**Pull request merged**
