### PR TITLE
Update cache keys when user name is changed

### PR DESCRIPTION
**Pull request by tsauerwein**
Related to https://github.com/c2corg/v6_api/issues/362

### CODE REVIEW

**Comment by asaunier** [comment]
Looks good.
I guess we have to reimport the DB if we want to push this change to demo?

**Comment by tsauerwein** [comment]
It would be enough to re-create the stored procedures:
https://github.com/c2corg/v6_api/blob/a46ff8f540f8ad603f2abfdd04c0629c17a1edc8/c2corg_api/models/cache_version.py#L40-L275

If not, this is not very critical. It could be done the next time we have to run the migration again.

Thanks for the review!

**Comment by asaunier** [comment]
OK!

I have updated the demo and recreated the procedures by hand in the DB.

**Comment by tsauerwein** [comment]
Cool, thanks!

**Pull request merged**
