### PR TITLE
When asked doc type is wrong, returns 404 io 200

### PR DESCRIPTION
**Pull request by cbeauchesne**
Fix for #707.

So, basicly, if a document is asked, the API look for it in a cache. The cache key does not include the document type : 

https://github.com/c2corg/v6_api/blob/3a5d5202da0ee49903b7ce495e141c41dce27892/c2corg_api/models/cache_version.py#L166

and 

https://github.com/c2corg/v6_api/blob/3a5d5202da0ee49903b7ce495e141c41dce27892/c2corg_api/views/document.py#L121

<small>Note that on the second line, `custom_cache_key` is sent in place of document_type... As far as I know, it does not cause a bug, hopefully...</small>

In consequence, imagine that you have an area with id 123. From an empty cache, do :  

1. `/routes/123`=> 404 ✅  
2. `/areas/123`=> 200 and the API save the doc in the cache
2. `/areas/123`=> 200, served from the cache 👍 
2. `/routes/123`=> 200, area #123 served from the cache, instead of 404 😡 

What I've done ? 

Considering that the philosophy followed by the API is to precise document types in URL, I've changed the `document_type` argument to mandatory on `get_cache_key()` : 

https://github.com/c2corg/v6_api/pull/752/files#diff-71235d266344278ce3ed31500c0df856R166

And small hack : history entry point does not precise the document type : `/document/124/history/fr`.

For this, I've used the generic `DOCUMENT_TYPE` type : 

https://github.com/c2corg/v6_api/pull/752/files#diff-d997b23b03a7bb5f76a2c2297fc55b6bR35

Sorry for this big commit, but it appears that there are quite a lot of boilerplate code in the API.

@asaunier, @b_b, would it be possible that you have a look on this commit ? :pray:

### CODE REVIEW

**Comment by tsauerwein** [comment]
> * `/routes/123`=> 404 white_check_mark
> 
> * `/areas/123`=> 200 and the API save the doc in the cache
> 
> * `/areas/123`=> 200, served from the cache +1
> 
> * `/routes/123`=> 200, served from the cache

Sorry, I didn't read everything in your description. But it is not possible that there is an area and a route with the same document-id. All documents, no matter what type, have a row in the `documents` table. So, the document-id is unique.

**Comment by cbeauchesne** [comment]
@tsauerwein yes, that's the point : the document served in the 4th request `/routes/123`** is the area**.  

You can easily try in prod: just look for a random document, request it with it's good document type, **then** request it with another document type.

**Comment by cbeauchesne** [comment]
And f**k, Travis has updated ubuntu from 14 to 16, it breaks the CI.

**Comment by cbeauchesne** [comment]
Thanks for the review @asaunier.

The demo server is actually down for a reason I ignore : https://api.demov6.camptocamp.org => I'l try to have look, but very little chance that I understand what's hapenning. Maybe @mfournier  ?

**Pull request merged**
