### PR TITLE
Use a default geometry

### PR DESCRIPTION
**Pull request by tsauerwein**
See https://github.com/c2corg/v6_api/issues/144#issuecomment-192289223

> To summarize, the motivation is
> 
> * to have a location for routes and outings that do not have a geometry, so that they are taken into account when doing a spatial search.
> * to have a point geometry for routes and outings which can be used to display them on the map in list/filter views (the full track will be used for the detail view).

To do:

- [x] Field `geom` of model `Geometry` is always a point, tracks for routes and outings are stored in `geom_detail`.
- [x] Adapt the migration script
  - [x] Set the default geom for outings and routes that already have a track (e.g. using [ST_Line_Interpolate_Point](http://postgis.net/docs/manual-1.5/ST_Line_Interpolate_Point.html)).
  - [x] If a route does not have a track, take the center of the convex hull of all associated waypoints.
  - [x] For outings without track, take the default geometry of the associated route(s).
  - [x] For outings and routes, set the new default geometry on all geometry versions.
- [x] Adapt the web-services
 - [x] When creating a route, and a track is given, use the track to set the default geometry. If not use the point of the main waypoint.
 - [x] When creating an outing, take the default geometry of the associated route.
- [x] The default geometry can be edited manually by changing `geometry.geom`.

Closes https://github.com/c2corg/v6_api/issues/144

### CODE REVIEW

**Comment by tsauerwein** [comment]
Ready to review.

**Comment by asaunier** [comment]
A minor comment else it looks excellent to me!

**Comment by asaunier** [comment]
By the way doing something similar for the images (later...) would be useful too.
And a bit challenging. For instance we could use the gps track of an associated outing to interpolate the coordinates of images using their datetime...

**Comment by asaunier** [comment]
> Makes sense. I moved it to models.utils.

OK, for me you can feel free to merge.

**Comment by tsauerwein** [comment]
Thanks for the review!

**Pull request merged**
